---
#
# Installation of BigBlueButton on a Ubuntu 18.04 (bionic) server.
#
# https://docs.bigbluebutton.org/2.4/install.html#before-you-install
#

- name: BigBlueButton installation
  hosts: all
  tasks:
    - name: Check locales
      ansible.builtin.include_tasks:
        file: tasks/locales.yml
        apply:
          tags: locales
      tags: locales
    - name: Check prerequisites for BigBlueButton installation
      ansible.builtin.include_tasks:
        file: tasks/prerequisites.yml
        apply:
          tags: check
      tags: check
    - name: Install BigBlueButton
      ansible.builtin.include_tasks:
        file: tasks/bbb-install.yml
        apply:
          tags: install
      tags: install
