---
#
# Installation of BigBlueButton on a Ubuntu 18.04 (bionic) server.
#
# https://docs.bigbluebutton.org/2.4/install.html#before-you-install
#

- name: Locales configuration
  hosts: all
  tasks:
    - name: Check and config locales
      ansible.builtin.include_tasks:
        file: tasks/locales.yml
        apply:
          tags: locales
      tags: locales
- name: Coturn installation
  hosts: Coturn_servers
  tasks:
    - name: Install coturn
      ansible.builtin.include_tasks:
        file: tasks/coturn.yml
        apply:
          tags: coturn
      tags: coturn
- name: BigBlueButton installation
  hosts: Bigbluebutton_servers
  tasks:
    - name: Check prerequisites for BigBlueButton installation
      ansible.builtin.include_tasks:
        file: tasks/prerequisites.yml
        apply:
          tags: check
      tags: check
    - name: Install BigBlueButton
      ansible.builtin.include_tasks:
        file: tasks/bbb-install.yml
        apply:
          tags: install
      tags: install
