---
#
# The followings tasks check that the host has hardware and system requirements
# to install BigBlueButton.
# See: https://docs.bigbluebutton.org/2.4/install.html#before-you-install
# 
# Some requirements differ between hosts used for testing or in production.
# In this case, the task is tagged with `dev` or `prod` respectively.
# Use `--skip-tags dev` when deploying to a production server or
# use `--skip-tags prod` when deploying to a test server.
#

- name: check if locale configuration is correct
  ansible.builtin.shell:
    cmd: cat /etc/default/locale | grep ^LANG=
  register: locale
  changed_when: False
  failed_when: locale.stdout != 'LANG=en_US.UTF-8'
- name: check if the server supports IPV6
  ansible.builtin.shell:
    cmd: ip addr | grep "inet6 ::1/128 scope host"
  changed_when: False
- name: check if the OS is Ubuntu 18.04
  ansible.builtin.shell:
    cmd: grep DISTRIB_DESCRIPTION /etc/lsb-release | cut -b 22-33
  register: distribution
  changed_when: False
  failed_when: distribution.stdout != "Ubuntu 18.04"
- name: check if the server running Linux kernel 4.x or newer
  ansible.builtin.shell:
    cmd: uname -r | cut -d'.' -f 1
  register: kernel
  changed_when: False
  failed_when: kernel.stdout | int < 4
- name: check if the server has 16Gi of memory (for production)
  ansible.builtin.shell:
    cmd: free -h | grep ^Mem | tr -s ' ' | cut -d' ' -f 2 | sed 's/Gi//g'
  register: memory
  changed_when: False
  failed_when: memory.stdout | float < 15.0
  tags: prod
- name: check if the server has 8Gi of memory (for development)
  ansible.builtin.shell:
    cmd: free -h | grep ^Mem | tr -s ' ' | cut -d' ' -f 2 | sed -r 's/G[i]?//g'
  register: memory
  changed_when: False
  failed_when: memory.stdout | float < 7.0
  tags: dev
- name: check if the server has at least 8 CPU cores (for production)
  ansible.builtin.shell:
    cmd: grep -c ^processor /proc/cpuinfo
  register: cpu
  changed_when: False
  failed_when: cpu.stdout | int < 8 
  tags: prod
- name: check if the server has at least 4 CPU cores (for development)
  ansible.builtin.shell:
    cmd: grep -c ^processor /proc/cpuinfo
  register: cpu
  changed_when: False
  failed_when: cpu.stdout | int < 4 
  tags: dev
